empresa_index:
    path:     /
    defaults: { _controller: "EmpresaBundle:Empresa:index" }
    methods:  [GET, POST]

empresa_show:
    path:     /{id}/show
    defaults: { _controller: "EmpresaBundle:Empresa:show" }
    requirements:
        format: json

empresa_search:
    path:     /{search}/search
    defaults: { _controller: "EmpresaBundle:Empresa:search" }
    requirements:
        format: json

empresa_new:
    path:     /new
    defaults: { _controller: "EmpresaBundle:Empresa:new" }
    methods:  [GET, POST]

empresa_edit:
    path:     /{id}/edit
    defaults: { _controller: "EmpresaBundle:Empresa:edit" }
    methods:  [GET, POST]

empresa_delete:
    path:     /delete/{id}
    defaults: { _controller: "EmpresaBundle:Empresa:delete" }
    methods:  GET

