empresa:
    resource: "@EmpresaBundle/Resources/config/routing.yml"
    prefix:   /
user_routes:
    prefix:   /
    resource: "@UserBundle/Controller"
index_routes:
    prefix:   /
    resource: "@EmpresaBundle/Controller"


