security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Arca\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_USER:       [ROLE_EMPRESA_CREATE]
        ROLE_ADMIN:       [ROLE_USER, ROLE_EVENT_CREATE]
        ROLE_SUPER_ADMIN: [ ROLE_USER ,  ROLE_ADMIN ,  ROLE_ALLOWED_TO_SWITCH ]

    providers:
        database:
            entity: { class: UserBundle:User} #//, property: username
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] } #já deixa definido um usuário pra entrar do tipo user
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] } #já deixa definido um usuário pra entrar do tipo admin

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login_form
            logout:
                path:   logout #rota pra deslogar
                target: index  #rota que será enviado quando deslogar
            anonymous: ~
            switch_user: ~
            #http_basic:
            #    realm: "Secured Demo Area"
            remember_me:
                key: "Order 1138"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/empresa, roles: ROLE_ADMIN }